In [0]:
import numpy as np
import pandas as pd

In [0]:
data = pd.read_csv('/content/RUB_USD.csv')
N = len(data['Date'])
tau = int((N + 1) / 2)
xt = data['RUB/USD']

In [54]:
X = np.array([xt[i:(i+tau)] for i in range(N-tau+1)])
n = len(X[0])
X

array([[33.08  , 32.83  , 32.83  , ..., 73.0339, 71.7047, 72.0491],
       [32.83  , 32.83  , 32.88  , ..., 71.7047, 72.0491, 71.908 ],
       [32.83  , 32.88  , 32.97  , ..., 72.0491, 71.908 , 71.4034],
       ...,
       [73.0339, 71.7047, 72.0491, ..., 67.4239, 67.4779, 67.5646],
       [71.7047, 72.0491, 71.908 , ..., 67.4779, 67.5646, 67.8954],
       [72.0491, 71.908 , 71.4034, ..., 67.5646, 67.8954, 68.2624]])

In [55]:
C = 1 / n * X.transpose().dot(X)
C

array([[2655.21847289, 2657.094128  , 2659.01716531, ..., 2998.1995522 ,
        2998.44887768, 2998.78559883],
       [2657.094128  , 2659.68829094, 2661.5332281 , ..., 3000.65077294,
        3000.90378576, 3001.23026056],
       [2659.01716531, 2661.5332281 , 2664.09688374, ..., 3003.10122821,
        3003.33746095, 3003.66705566],
       ...,
       [2998.1995522 , 3000.65077294, 3003.10122821, ..., 3751.54716659,
        3751.01102669, 3750.65008438],
       [2998.44887768, 3000.90378576, 3003.33746095, ..., 3751.01102669,
        3750.7531258 , 3750.35075155],
       [2998.78559883, 3001.23026056, 3003.66705566, ..., 3750.65008438,
        3750.35075155, 3750.22482673]])

In [65]:
w, V = np.linalg.eig(C)
W = np.diag(w)
W

array([3.27212666e+06, 4.67286316e+04, 7.41561687e+03, 4.22961474e+03,
       3.32622213e+03, 1.98370937e+03, 1.92284961e+03, 1.21024691e+03,
       9.40686714e+02, 5.34561482e+02, 2.76325467e+02, 1.73982687e+02,
       1.71848461e+02, 1.09760769e+02, 1.07565821e+02, 8.90644661e+01,
       8.65456343e+01, 5.97830548e+01, 5.73185025e+01, 4.51847908e+01,
       4.36621365e+01, 3.20668607e+01, 3.13743748e+01, 2.98040407e+01,
       2.82569848e+01, 2.66516156e+01, 2.65374551e+01, 2.57373447e+01,
       2.55812027e+01, 2.36489015e+01, 2.26286111e+01, 2.21479744e+01,
       2.18277468e+01, 2.15207827e+01, 1.97405145e+01, 1.94309933e+01,
       1.92415832e+01, 1.76282805e+01, 1.75616300e+01, 1.62249421e+01,
       1.59044046e+01, 1.56625172e+01, 1.49510131e+01, 1.41799198e+01,
       1.36058662e+01, 1.31317595e+01, 1.31410049e+01, 1.26423786e+01,
       1.26771177e+01, 1.23356050e+01, 1.22028924e+01, 1.21946148e+01,
       1.19161221e+01, 1.11433207e+01, 1.09225718e+01, 1.01816758e+01,
      

In [57]:
V.transpose().dot(C).dot(V) # =W
#np.abs(np.linalg.det(C) - np.prod(w)) < 1e-3

array([[ 3.27212666e+06, -5.82076609e-10,  1.28056854e-09, ...,
         4.54747351e-12, -1.86446414e-11, -7.63975549e-11],
       [ 1.41881173e-10,  4.67286316e+04, -1.63709046e-11, ...,
         3.00701686e-11,  4.00603994e-11, -4.94537744e-12],
       [-2.91038305e-10, -1.43245416e-11,  7.41561687e+03, ...,
        -2.88409296e-11, -3.67363917e-11,  1.66069380e-11],
       ...,
       [ 6.37115510e-12,  1.75008618e-12,  6.25946354e-13, ...,
         1.46343459e-02,  1.48131560e-09,  3.93359305e-09],
       [-2.92243437e-12, -4.77332393e-13,  3.05173895e-12, ...,
         1.48164398e-09,  1.46609614e-02, -7.01732340e-10],
       [-2.90790907e-11, -2.78524623e-13,  5.31414318e-13, ...,
         3.93344027e-09, -7.01656129e-10,  1.46489876e-02]])

In [59]:
Y = V.transpose().dot(X)
Y

array([[-1.50450592e+03, -1.50584197e+03, -1.50716773e+03, ...,
        -1.83753640e+03, -1.83741821e+03, -1.83734925e+03],
       [-3.24343839e+02, -3.24952442e+02, -3.25529669e+02, ...,
         1.63693191e+02,  1.62756301e+02,  1.61873975e+02],
       [ 1.44176738e+02,  1.44649179e+02,  1.45106380e+02, ...,
         1.07728700e+02,  1.07914612e+02,  1.08188495e+02],
       ...,
       [-1.32443538e-01,  7.77601860e-04,  7.56195769e-02, ...,
        -7.53116710e-02,  4.80541760e-02,  4.55657011e-02],
       [ 1.01199516e-01, -8.50860849e-02,  3.40285765e-02, ...,
         9.80431994e-02, -2.48708790e-02, -2.87303093e-02],
       [-4.48599265e-02,  4.91740273e-02,  4.39157051e-02, ...,
         2.27765554e-02, -2.52360468e-03, -6.22491434e-03]])

In [71]:
r = int(tau * 2 / 3)
Vr = V[:r]
Temp = Y.transpose()[:r]
Yr = Temp.transpose()
Vr.dot(Yr)

array([[33.08      , 32.83      , 32.83000001, ..., 52.0432    ,
        50.5526    , 50.98430003],
       [32.82999999, 32.83      , 32.88000003, ..., 50.55259996,
        50.98430002, 49.94699999],
       [32.82999998, 32.87999996, 32.97000001, ..., 50.98429999,
        49.94699997, 50.97390001],
       ...,
       [52.0432    , 50.55260004, 50.98430001, ..., 61.4918    ,
        61.39820002, 61.28300002],
       [50.5526    , 50.98429997, 49.94700004, ..., 61.39819997,
        61.283     , 61.1305    ],
       [50.98429998, 49.947     , 50.9739    , ..., 61.28299998,
        61.13049999, 60.9423    ]])

In [0]:
def S(P, V):
  return np.sum(P*V)